<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CursoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('Curso')->insert(
            [
                [
                    "Identificador" => "GP101",
                    "Nombre" => "TEORÍA DEL ESTADO",
                    "CantidadCreditos" => "4",
                    "Semestre" => "1",
                    "CantidadHorasTeoricas" => "48",
                    "CantidadHorasPracticas" => "32",
                    "Tipo" => "ES",
                    "CodigoCurricula" => "1",
                ],
                [
                    "Identificador" => "GP102",
                    "Nombre" => "ESTADO Y POLÍTICAS PÚBLICAS",
                    "CantidadCreditos" => "4",
                    "Semestre" => "1",
                    "CantidadHorasTeoricas" => "48",
                    "CantidadHorasPracticas" => "32",
                    "Tipo" => "ES",
                    "CodigoCurricula" => "1",
                ],
                [
                    "Identificador" => "GP103",
                    "Nombre" => "GESTIÓN PÚBLICA POR RESULTADOS",
                    "CantidadCreditos" => "4",
                    "Semestre" => "1",
                    "CantidadHorasTeoricas" => "48",
                    "CantidadHorasPracticas" => "32",
                    "Tipo" => "ES",
                    "CodigoCurricula" => "1",
                ],
                [
                    "Identificador" => "GP104",
                    "Nombre" => "LIDERAZGO Y HABILIDADES GERENCIALES",
                    "CantidadCreditos" => "4",
                    "Semestre" => "1",
                    "CantidadHorasTeoricas" => "48",
                    "CantidadHorasPracticas" => "32",
                    "Tipo" => "ES",
                    "CodigoCurricula" => "1",
                ],
                [
                    "Identificador" => "GP205",
                    "Nombre" => "GESTIÓN DE RECURSOS HUMANOS",
                    "CantidadCreditos" => "4",
                    "Semestre" => "2",
                    "CantidadHorasTeoricas" => "48",
                    "CantidadHorasPracticas" => "32",
                    "Tipo" => "ES",
                    "CodigoCurricula" => "1",
                ],
                [
                    "Identificador" => "GP206",
                    "Nombre" => "PLANIFICACIÓN ESTRATÉGICA",
                    "CantidadCreditos" => "4",
                    "Semestre" => "2",
                    "CantidadHorasTeoricas" => "48",
                    "CantidadHorasPracticas" => "32",
                    "Tipo" => "ES",
                    "CodigoCurricula" => "1",
                ],
                [
                    "Identificador" => "GP207",
                    "Nombre" => "ADQUISICIONES Y CONTRATACIONES DEL ESTADO",
                    "CantidadCreditos" => "4",
                    "Semestre" => "2",
                    "CantidadHorasTeoricas" => "48",
                    "CantidadHorasPracticas" => "32",
                    "Tipo" => "ES",
                    "CodigoCurricula" => "1",
                ],
                [
                    "Identificador" => "GP208",
                    "Nombre" => "IMPLICANCIAS MORALES Y ÉTICAS DE LA GESTIÓN PÚBLICA",
                    "CantidadCreditos" => "4",
                    "Semestre" => "2",
                    "CantidadHorasTeoricas" => "48",
                    "CantidadHorasPracticas" => "32",
                    "Tipo" => "ES",
                    "CodigoCurricula" => "1",
                ],
                [
                    "Identificador" => "GP39",
                    "Nombre" => "ANÁLISIS, DISEÑO Y EVALUACIÓN DE POLÍTICAS PÚBLICAS",
                    "CantidadCreditos" => "4",
                    "Semestre" => "3",
                    "CantidadHorasTeoricas" => "48",
                    "CantidadHorasPracticas" => "32",
                    "Tipo" => "ES",
                    "CodigoCurricula" => "1",
                ],
                [
                    "Identificador" => "GP310",
                    "Nombre" => "FINANZAS PÚBLICAS",
                    "CantidadCreditos" => "4",
                    "Semestre" => "3",
                    "CantidadHorasTeoricas" => "48",
                    "CantidadHorasPracticas" => "32",
                    "Tipo" => "ES",
                    "CodigoCurricula" => "1",
                ],
                [
                    "Identificador" => "GP311",
                    "Nombre" => "ESTADÍSTICA APLICADA",
                    "CantidadCreditos" => "4",
                    "Semestre" => "3",
                    "CantidadHorasTeoricas" => "48",
                    "CantidadHorasPracticas" => "32",
                    "Tipo" => "ES",
                    "CodigoCurricula" => "1",
                ],
                [
                    "Identificador" => "GP312",
                    "Nombre" => "PROYECTOS DE INVERSIÓN PÚBLICA",
                    "CantidadCreditos" => "4",
                    "Semestre" => "3",
                    "CantidadHorasTeoricas" => "48",
                    "CantidadHorasPracticas" => "32",
                    "Tipo" => "ES",
                    "CodigoCurricula" => "1",
                ],
                [
                    "Identificador" => "GP413",
                    "Nombre" => "AUDITORÍA Y PREVENCIÓN DE RIESGOS",
                    "CantidadCreditos" => "4",
                    "Semestre" => "4",
                    "CantidadHorasTeoricas" => "48",
                    "CantidadHorasPracticas" => "32",
                    "Tipo" => "ES",
                    "CodigoCurricula" => "1",
                ],
                [
                    "Identificador" => "GP414",
                    "Nombre" => "SEMINARIO DE TESIS I",
                    "CantidadCreditos" => "4",
                    "Semestre" => "4",
                    "CantidadHorasTeoricas" => "48",
                    "CantidadHorasPracticas" => "32",
                    "Tipo" => "ES",
                    "CodigoCurricula" => "1",
                ],
                [
                    "Identificador" => "GP415",
                    "Nombre" => "SEMINARIO DE TESIS II",
                    "CantidadCreditos" => "4",
                    "Semestre" => "4",
                    "CantidadHorasTeoricas" => "48",
                    "CantidadHorasPracticas" => "32",
                    "Tipo" => "ES",
                    "CodigoCurricula" => "1",
                ],
                [
                    "Identificador" => "GP416",
                    "Nombre" => "SEMINARIO DE TESIS III",
                    "CantidadCreditos" => "4",
                    "Semestre" => "4",
                    "CantidadHorasTeoricas" => "48",
                    "CantidadHorasPracticas" => "32",
                    "Tipo" => "ES",
                    "CodigoCurricula" => "1",
                ],
                [
                    "Identificador" => "DD101",
                    "Nombre" => "TEORÍA DEL ESTADO",
                    "CantidadCreditos" => "4",
                    "Semestre" => "1",
                    "CantidadHorasTeoricas" => "48",
                    "CantidadHorasPracticas" => "32",
                    "Tipo" => "ES",
                    "CodigoCurricula" => "2",
                ],
                [
                    "Identificador" => "DD102",
                    "Nombre" => "TEORÍA GENERAL DEL DERECHO",
                    "CantidadCreditos" => "4",
                    "Semestre" => "1",
                    "CantidadHorasTeoricas" => "48",
                    "CantidadHorasPracticas" => "32",
                    "Tipo" => "ES",
                    "CodigoCurricula" => "2",
                ],
                [
                    "Identificador" => "DD103",
                    "Nombre" => "TEORÍA DEL DERECHO CONSTITUCIONAL",
                    "CantidadCreditos" => "4",
                    "Semestre" => "1",
                    "CantidadHorasTeoricas" => "48",
                    "CantidadHorasPracticas" => "32",
                    "Tipo" => "ES",
                    "CodigoCurricula" => "2",
                ],
                [
                    "Identificador" => "DD104",
                    "Nombre" => "TEORÍA DEL DERECHO PENAL",
                    "CantidadCreditos" => "4",
                    "Semestre" => "1",
                    "CantidadHorasTeoricas" => "48",
                    "CantidadHorasPracticas" => "32",
                    "Tipo" => "ES",
                    "CodigoCurricula" => "2",
                ],
                [
                    "Identificador" => "DD205",
                    "Nombre" => "TEORÍA DEL DERECHO CIVIL",
                    "CantidadCreditos" => "4",
                    "Semestre" => "2",
                    "CantidadHorasTeoricas" => "48",
                    "CantidadHorasPracticas" => "32",
                    "Tipo" => "ES",
                    "CodigoCurricula" => "2",
                ],
                [
                    "Identificador" => "DD206",
                    "Nombre" => "TEORÍA DEL PROCESO PENAL",
                    "CantidadCreditos" => "4",
                    "Semestre" => "2",
                    "CantidadHorasTeoricas" => "48",
                    "CantidadHorasPracticas" => "32",
                    "Tipo" => "ES",
                    "CodigoCurricula" => "2",
                ],
                [
                    "Identificador" => "DD207",
                    "Nombre" => "TEORÍA DEL PROCESO CIVIL",
                    "CantidadCreditos" => "4",
                    "Semestre" => "2",
                    "CantidadHorasTeoricas" => "48",
                    "CantidadHorasPracticas" => "32",
                    "Tipo" => "ES",
                    "CodigoCurricula" => "2",
                ],
                [
                    "Identificador" => "DD208",
                    "Nombre" => "FILOSOFÍA DEL DERECHO",
                    "CantidadCreditos" => "4",
                    "Semestre" => "2",
                    "CantidadHorasTeoricas" => "48",
                    "CantidadHorasPracticas" => "32",
                    "Tipo" => "ES",
                    "CodigoCurricula" => "2",
                ],
                [
                    "Identificador" => "DD309",
                    "Nombre" => "SEMINARIO DE TESIS I: EL ESTADO DEL ARTE",
                    "CantidadCreditos" => "5",
                    "Semestre" => "3",
                    "CantidadHorasTeoricas" => "32",
                    "CantidadHorasPracticas" => "96",
                    "Tipo" => "ES",
                    "CodigoCurricula" => "2",
                ],
                [
                    "Identificador" => "DD310",
                    "Nombre" => "SEMINARIO DE TESIS II: EL PROYECTO DE TESIS",
                    "CantidadCreditos" => "5",
                    "Semestre" => "3",
                    "CantidadHorasTeoricas" => "32",
                    "CantidadHorasPracticas" => "96",
                    "Tipo" => "ES",
                    "CodigoCurricula" => "2",
                ],
                [
                    "Identificador" => "DD411",
                    "Nombre" => "SEMINARIO DE TESIS III: EL MARCO TEÓRICO I",
                    "CantidadCreditos" => "5",
                    "Semestre" => "4",
                    "CantidadHorasTeoricas" => "32",
                    "CantidadHorasPracticas" => "96",
                    "Tipo" => "ES",
                    "CodigoCurricula" => "2",
                ],
                [
                    "Identificador" => "DD412",
                    "Nombre" => "SEMINARIO DE TESIS IV: EL MARCO TEÓRICO II",
                    "CantidadCreditos" => "5",
                    "Semestre" => "4",
                    "CantidadHorasTeoricas" => "32",
                    "CantidadHorasPracticas" => "96",
                    "Tipo" => "ES",
                    "CodigoCurricula" => "2",
                ],
                [
                    "Identificador" => "DD513",
                    "Nombre" => "SEMINARIO DE TESIS V: RECOLECCIÓN Y ANÁLISIS DE DATOS",
                    "CantidadCreditos" => "5",
                    "Semestre" => "5",
                    "CantidadHorasTeoricas" => "32",
                    "CantidadHorasPracticas" => "96",
                    "Tipo" => "ES",
                    "CodigoCurricula" => "2",
                ],
                [
                    "Identificador" => "DD514",
                    "Nombre" => "SEMINARIO DE TESIS VI: DISEÑO Y FUNDAMENTACIÓN DEL MODELO DE INVESTIGACIÓN",
                    "CantidadCreditos" => "5",
                    "Semestre" => "5",
                    "CantidadHorasTeoricas" => "32",
                    "CantidadHorasPracticas" => "96",
                    "Tipo" => "ES",
                    "CodigoCurricula" => "2",
                ],
                [
                    "Identificador" => "DD615",
                    "Nombre" => "SEMINARIO DE TESIS VII: REDACCIÓN DEL INFORME FINAL",
                    "CantidadCreditos" => "5",
                    "Semestre" => "6",
                    "CantidadHorasTeoricas" => "32",
                    "CantidadHorasPracticas" => "96",
                    "Tipo" => "ES",
                    "CodigoCurricula" => "2",
                ],
                [
                    "Identificador" => "DD616",
                    "Nombre" => "SEMINARIO DE TESIS VIII: DEFENSA PRELIMINAR DE LA TESIS",
                    "CantidadCreditos" => "5",
                    "Semestre" => "6",
                    "CantidadHorasTeoricas" => "32",
                    "CantidadHorasPracticas" => "96",
                    "Tipo" => "ES",
                    "CodigoCurricula" => "2",
                ],
            ]
        );
    }
}
