<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProgramaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('Programa')->insert(
            [
                [
                    'Identificador' => 'P185',
                    'Nombre' => 'Ciencias con Mención en Microbiología',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 1,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P200',
                    'Nombre' => 'Ciencias con Mención en Biología Molecular y Bioquímica Clínica',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 1,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P80',
                    'Nombre' => 'Ciencias con Mención en Ingeniería Ambiental',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 1,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P89',
                    'Nombre' => 'Ciencias con Mención en Ecología y Conservación',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 1,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P97',
                    'Nombre' => 'Administración con Mención en Gerencia Empresarial',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 2,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P98',
                    'Nombre' => 'Administración con Mención en Gerencia Pública',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 2,
                    'CodigoCoordinador' => 4,
                ],
                [
                    'Identificador' => 'P99',
                    'Nombre' => 'Ciencias con Mención en Proyectos de Inversión',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 2,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P102',
                    'Nombre' => 'Ciencias con Mención en Control y Auditoría en la Gestión Gubernamental',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 2,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P92',
                    'Nombre' => 'Ciencias - Tributación y Asesoría Fiscal',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 2,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P184',
                    'Nombre' => 'Ciencias con Mención en Matemática Aplicada',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 3,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P188',
                    'Nombre' => 'Ciencias con Mención en Gerencia en Tecnología de Información',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 3,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P189',
                    'Nombre' => 'Ciencias con Mención en Informática y Sistemas',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 3,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P72',
                    'Nombre' => 'Ciencias de la Educación con Mención en Investigación y Docencia',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 4,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P73',
                    'Nombre' => 'Ciencias de la Educación con Mención en Psicopedagogía',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 4,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P74',
                    'Nombre' => 'Ciencias de la Educación con Mención en Docencia y Gestión Universitaria',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 4,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P75',
                    'Nombre' => 'Ciencias de la Educación con Mención en Gerencia Educativa Estratégica',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 4,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P76',
                    'Nombre' => 'Ciencias de la Educación con Mención en Didáctica del Idioma Inglés',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 4,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P77',
                    'Nombre' => 'Ciencias Sociales con Mención en Gestión Pública y Gerencia Social',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 4,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P78',
                    'Nombre' => 'Psicología con Mención en Psicología Clínica',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 4,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P79',
                    'Nombre' => 'Psicología con Mención en Psicología Organizacional',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 4,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P105',
                    'Nombre' => 'Ciencias con Mención en Docencia Universitaria e Investigación Educativa',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 4,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P106',
                    'Nombre' => 'Gestión de la Calidad y Acreditación Educativa',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 4,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P192',
                    'Nombre' => 'Ciencias de la Educación con Mención en Educación Intercultural',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 4,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P193',
                    'Nombre' => 'Ciencias de la Educación con Mención en Administración de Instituciones Educativas y Tecnologías de la Información',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 4,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P194',
                    'Nombre' => 'Ciencias de la Educación con Mención en Estimulación Temprana y Gestión del Talento',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 4,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P195',
                    'Nombre' => 'Ciencias de la Educación con Mención en Evaluación y Acreditación Educativa',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 4,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P196',
                    'Nombre' => 'Ciencias de la Educación con Mención en Teoría y Planeamiento Curricular',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 4,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P197',
                    'Nombre' => 'Ciencias de la Educación con Mención en Tecnologías de la Información e Informática Educativa',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 4,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P198',
                    'Nombre' => 'Ciencias Sociales con Mención en Gobernabilidad, Descentralización y Reforma del Estado',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 4,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P199',
                    'Nombre' => 'Ciencias Sociales con Mención en Políticas Sociales: Gerencia Social',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 4,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P186',
                    'Nombre' => 'Derecho con Mención en Judicial y Fiscal',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 5,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P64',
                    'Nombre' => 'Derecho con Mención en Derecho Civil y Procesal Civil',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 5,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P65',
                    'Nombre' => 'Derecho con Mención en Derecho Constitucional y Procesal Constitucional',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 5,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P66',
                    'Nombre' => 'Derecho con Mención en Derecho Empresarial',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 5,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P67',
                    'Nombre' => 'Derecho con Mención en Derecho Penal y Procesal Penal',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 5,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P68',
                    'Nombre' => 'Derecho del Trabajo y de la Seguridad Social',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 5,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P93',
                    'Nombre' => 'Derecho con Mención en Ciencias Penales',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 5,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P94',
                    'Nombre' => 'Derecho con Mención en Constitucional y Gobernabilidad',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 5,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P95',
                    'Nombre' => 'Derecho con Mención en Civil y Comercial',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 5,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P62',
                    'Nombre' => 'Ciencias de Enfermería',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 6,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P60',
                    'Nombre' => 'Ciencias Pecuarias con Mención en Producción Animal',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 7,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P81',
                    'Nombre' => 'Ciencias de la Ingeniería Mecánica y Eléctrica con Mención en Energía',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 8,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P54',
                    'Nombre' => 'Gestión Integrado de los Recurso Hídricos',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 9,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P85',
                    'Nombre' => 'Ciencias con Mención en Ingeniería Hidráulica',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 10,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P82',
                    'Nombre' => 'Ingeniería de Sistemas con Mención en Gerencia de Tecnologías de la Información y Gestión del Software',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 10,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P83',
                    'Nombre' => 'Ciencias con Mención en Ordenamiento Territorial y Desarrollo Urbano',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 10,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P84',
                    'Nombre' => 'Gerencia de Obras y Construcción',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 10,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P183',
                    'Nombre' => 'Ciencias - Gestión de la Calidad e Inocuidad de Alimentos',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 11,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P190',
                    'Nombre' => 'Ciencias con Mención en Ingeniería de Procesos Industriales',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 11,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P187',
                    'Nombre' => 'Ciencias - Auditoría Médica',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 12,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P191',
                    'Nombre' => 'Odontología con Mención en Ortodoncia',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 12,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P87',
                    'Nombre' => 'Ciencias con Mención en Gerencia de Servicios de Salud',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 12,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P88',
                    'Nombre' => 'Salud Pública',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 12,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P91',
                    'Nombre' => 'Medicina',
                    'Tipo' => 'MA',
                    'CodigoFacultad' => 12,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P111',
                    'Nombre' => 'Ciencias Ambientales',
                    'Tipo' => 'DO',
                    'CodigoFacultad' => 1,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P115',
                    'Nombre' => 'Administración',
                    'Tipo' => 'DO',
                    'CodigoFacultad' => 2,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P116',
                    'Nombre' => 'Economía',
                    'Tipo' => 'DO',
                    'CodigoFacultad' => 2,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P117',
                    'Nombre' => 'Contabilidad',
                    'Tipo' => 'DO',
                    'CodigoFacultad' => 2,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P118',
                    'Nombre' => 'Ciencias de la Educación',
                    'Tipo' => 'DO',
                    'CodigoFacultad' => 4,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P119',
                    'Nombre' => 'Gestión Universitaria',
                    'Tipo' => 'DO',
                    'CodigoFacultad' => 4,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P121',
                    'Nombre' => 'Sociología',
                    'Tipo' => 'DO',
                    'CodigoFacultad' => 4,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P114',
                    'Nombre' => 'Derecho y Ciencia Política',
                    'Tipo' => 'DO',
                    'CodigoFacultad' => 5,
                    'CodigoCoordinador' => 1,
                ],
                [
                    'Identificador' => 'P113',
                    'Nombre' => 'Ciencias de Enfermería',
                    'Tipo' => 'DO',
                    'CodigoFacultad' => 6,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P108',
                    'Nombre' => 'Ciencias de la Ingeniería Mecánica y Eléctrica con Mención en Energía',
                    'Tipo' => 'DO',
                    'CodigoFacultad' => 8,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P107',
                    'Nombre' => 'Territorio y Urbanismo Sostenible',
                    'Tipo' => 'DO',
                    'CodigoFacultad' => 10,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P109',
                    'Nombre' => 'Ciencias de la Salud',
                    'Tipo' => 'DO',
                    'CodigoFacultad' => 12,
                    'CodigoCoordinador' => null,
                ],
                [
                    'Identificador' => 'P110',
                    'Nombre' => 'Medicina',
                    'Tipo' => 'DO',
                    'CodigoFacultad' => 12,
                    'CodigoCoordinador' => null,
                ],
            ]
        );
    }
}
